apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
specs:
  source:
    repoURL: 'https://github.com/chicaragua/ITA.git'
    path: 14.K8s.Jenkins/
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ci-cd
  syncPolicy:
    automated:
      prune: true
