apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
specs:
  destination:
    server: https://kubernetes.default.svc
    namespace: ci-cd
  project: default
  source:
    repoURL: https://github.com/chicaragua/ITA.git
    path: 14.K8s.Jenkins/
    targetRevision: master

  syncPolicy:
    automated:
      prune: true
